name: 'project-init'
description: 'Initializes the project environment with Node.js and pnpm and sets up caching for pnpm store.'
runs:
  using: composite
  steps:
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 22
    - uses: pnpm/action-setup@v4
      with:
        run_install: false
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store
    - run: pnpm install
      shell: bash
