name: build-test
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
      - uses: ./.github/actions/project-init
      - run: pnpm build
      - run: pnpm test
